stages:
  - stage_build
  - stage_test
  - stage_push
  - stage_develop
  - stage_deploy
  - stage_new_release



before_script:
  - echo "POSTGRES_HOST=$POSTGRES_HOST" >> .env
  - echo "POSTGRES_PORT=$POSTGRES_PORT" >> .env
  - echo "POSTGRES_NAME=$POSTGRES_NAME" >> .env
  - echo "POSTGRES_USER=$POSTGRES_USER" >> .env
  - echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" >> .env
  - echo "DEBUG=$DEBUG" >> .env
  - echo "SECRET_KEY=$SECRET_KEY" >> .env
  - echo "DJANGO_PORT=$DJANGO_PORT" >> .env
  - echo "BACKEND_DOMAIN=$BACKEND_DOMAIN" >> .env
  - echo "CORS_ALLOWED_ORIGINS=$CORS_ALLOWED_ORIGINS" >> .env
  - echo "IMAGE_VERSION=$IMAGE_VERSION" >> .env
  - echo "CI_REGISTRY_IMAGE=$CI_REGISTRY_IMAGE" >> .env


build_job:
  stage: stage_build
  tags: ["runner-test"]
  environment:
    name: server-test
  script:
    - cd docker
    - sudo docker compose --env-file ../.env build --no-cache web
  only:
    - main
    - develop
    - tags
    - merge_request
    

test_job:
  stage: stage_test
  tags: ["runner-test"]
  dependencies:
    - "build_job"
  needs:
    - job: build_job
  environment:
    name: server-test
  script:
    - sudo cat .env
    - cd docker
    - sudo docker compose --file docker-compose-postgres.yml --env-file ../.env up -d postgres
    - sudo docker compose --env-file ../.env run web python manage.py makemigrations
    - sudo docker compose --env-file ../.env run web python manage.py migrate  
    - sudo docker compose --env-file ../.env run web python manage.py test
  after_script:
    - cd docker
    - sudo docker compose --file docker-compose-postgres.yml down -v
  only:
    - main
    - develop
    - tags
    - merge_request


push_job:
  stage: stage_push
  tags: ["runner-test"]
  dependencies:
    - "test_job"
  needs:
    - job: test_job
  environment:
    name: server-test
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH == "main"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && ($CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main")'
      when: always
    - if: '$CI_COMMIT_TAG'
      when: always
  before_script:
      - echo "$CI_REGISTRY_PASSWORD" | sudo docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
  script: 
    - sudo docker tag "$CI_REGISTRY_IMAGE:$IMAGE_VERSION" "${CI_REGISTRY}:5050/${CI_PROJECT_NAME}:${IMAGE_VERSION}"
    - sudo docker push "${CI_REGISTRY}:5050/${CI_PROJECT_NAME}:${IMAGE_VERSION}"


develop_job:
  stage: stage_develop  # Ensure this stage is before deploy
  tags: ["runner-develop"]
  dependencies:
    - "push_job"
  needs:
    - job: push_job
    - job: test_job
  environment:
    name: server-develop
  variables:
    DEBUG: "True"
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"'
      when: always
  script:
    - cd docker
    - sudo docker compose --file docker-compose-postgres.yml --env-file ../.env up -d postgres
    - echo "$CI_REGISTRY_PASSWORD" | sudo docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - sudo docker pull "${CI_REGISTRY}:5050/${CI_PROJECT_NAME}:${IMAGE_VERSION}"
    - sudo docker tag "${CI_REGISTRY}:5050/${CI_PROJECT_NAME}:${IMAGE_VERSION}" "$CI_REGISTRY_IMAGE:$IMAGE_VERSION"
    - sudo docker compose down web
    - sudo docker compose --env-file ../.env  up -d


deploy_job:
  stage: stage_deploy  # Deploy is now after develop
  tags: ["runner-deploy"]
  dependencies:
    - "push_job"
  needs:
    - job: push_job
  when: manual
  environment:
    name: server-deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'
      when: always
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | sudo docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
  script:
    - cd docker
    - sudo docker pull "${CI_REGISTRY}:5050/${CI_PROJECT_NAME}:${IMAGE_VERSION}"
    - sudo docker tag "${CI_REGISTRY}:5050/${CI_PROJECT_NAME}:${IMAGE_VERSION}" "$CI_REGISTRY_IMAGE:$IMAGE_VERSION"
    - sudo docker compose down web
    - sudo docker compose --env-file ../.env up -d


new_release:
  stage: stage_new_release
  tags: ["runner-deploy"]
  dependencies:
    - "push_job"
  environment:
    name: server-deploy
  needs:
    - job: test_job
    - job: push_job
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | sudo docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
  script:
    - cd docker
    - sudo docker pull "${CI_REGISTRY}:5050/${CI_PROJECT_NAME}:${IMAGE_VERSION}"
    - sudo docker tag "${CI_REGISTRY}:5050/${CI_PROJECT_NAME}:${IMAGE_VERSION}" "$CI_REGISTRY_IMAGE:$IMAGE_VERSION"
    - sudo docker compose down web
    - sudo docker compose --env-file ../.env up -d
  rules:
    - if: "$CI_COMMIT_TAG"
      when: always
  release:
    tag_name: "$CI_COMMIT_TAG"
    description: "Release for $CI_COMMIT_TAG"


after_script:
  - sudo docker logout

