
services:
  postgres:
    image: postgres
    hostname: ${POSTGRES_HOST}
    container_name: ${POSTGRES_HOST}
    command: -p ${POSTGRES_PORT}
    restart: on-failure
    environment: 
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - "${POSTGRES_PORT}"
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - db-data:/var/lib/postgresql/data 
    networks: 
      - web_network_test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      retries: 5
      start_period: 30s

volumes:
  db-data:

networks:
  web_network_test:
